import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'About | Samablue',
    description: "Generated by create next app",
  };

export default function Home() {
  return (
    <div className="">
        about page
    </div>
  );
}
