import { Metadata } from "next";
import Image from "next/image";
import img1 from "../../public/images/img2.jpg";



export const metadata: Metadata = {
    title: 'Galerie',
    description: "Generated by create next app",
  };

export default function Gallery() {
  return (
    <div className="">
         <div className="text-center h-[360px] flex justify-center items-center bg-yellow-950 overflow-hidden fixed top-[65px] left-0 z-0 w-full" >
          <Image
            src={img1} 
            alt="Silos"
            placeholder="blur"
            loading="lazy" 
            className="w-full h-96 object-cover object-bottom opacity-70 absolute top-0 left-0"/>
        </div>
        <div className="relative z-10">
          <h1 className="text-5xl font-bold text-white shadow py-20 text-center">Exploration Visuelle</h1>
          <div className="bg-white h-screen">


          </div>
        </div> 
    </div>
  );
}
