import { Metadata } from "next";
import Image from "next/image";
import img1 from "../../public/images/img1.jpg";
import NewsPage from "@/components/NewsPage";



export const metadata: Metadata = {
    title: 'Nouveautès',
    description: "Generated by create next app",
  };

export default function Home() {
  return (
    <div className="">
         <div className="text-center h-[360px] flex justify-center items-center bg-yellow-950 overflow-hidden fixed top-[65px] left-0 z-0 w-full" >
          <Image
            src={img1} 
            alt="Silos"
            placeholder="blur"
            loading="lazy" 
            className="w-full h-96 object-cover object-bottom opacity-70 absolute top-0 left-0"/>
        </div>
        <div className="relative z-10">
          <h1 className="text-5xl font-bold text-white shadow py-20 text-center">Actualités & Dernières Nouvelles</h1>
          <div className=" bg-gray-50">
            <div className="w-full flex justify-center items-center">
              <p className="text-gray-600 text-sm text-center max-w-5xl pt-10 bg-yellow-50/30">
              {`Notre page d’actualités vous informe sur les derniers événements, innovations et collaborations du secteur agroalimentaire. Retrouvez nos participations aux salons, conférences et rencontres professionnelles. Restez connectés pour suivre l’évolution du marché et nos engagements stratégiques.`}
              </p>
            </div>
            <NewsPage/>
          </div>
        </div> 
    </div>
  );
}
