import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'News | Samablue',
    description: "Generated by create next app",
  };

export default function Home() {
  return (
    <div className="">
        News page
    </div>
  );
}
